version: "3"

services:
  backend-api-db-postgresql:
    image: postgres:latest
    restart: on-failure
    container_name: backend-api-lms-db-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=study_space_db
    networks:
      - kelompok-b12

  backend-api-db-mongodb:
    image: bitnami/mongodb:latest
    restart: on-failure
    container_name: backend-api-lms-db-mongodb
    ports:
      - "27017:20717"
    networks:
      - kelompok-b12
    environment:
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=study_space_db

networks:
  kelompok-b12: { }