name: Backend API Project for LMS Kelompok B12

on: 
  push:
   branches:
     - "master"
  pull_request:
    branches:
     - "dev"

jobs:
  tests:
   name: Testing Backend API LMS 
   runs-on: ubuntu-latest
   steps:
     - name: Clone repository to github testing enviroment
       uses: actions/checkout@v1

     - name: Setup Java Enviroment
       uses: actions/setup-java@v3
       with:
         java-version: "11"
         distribution: "temurin"
     
     - name: Restore Maven Cache Dependency
       uses: skjolber/maven-cache-github-action@v1
       with:
         step: restore

     - name: Running Testing
       run: mvn clean test verify

     - name: Preparing Code Coverage Reports
       run: rm -rfv ./env/cc/html && mv -v ./target/site/jacoco ./env/cc/html