name: Backend API Project for LMS Kelompok B12

on: 
  push:
   branches:
     - "master"
     - "dev"
  pull_request:
    branches:
     - "master"
     - "dev"

jobs:
  tests:
   name: Testing Backend API LMS 
   runs-on: ubuntu-latest
   steps:
     - name: Clone repository to github testing enviroment
       uses: actions/checkout@v1

     - name: Setup Java Enviroment
       uses: actions/setup-java@v3
       with:
         java-version: "11"
         distribution: "temurin"
     
    #  - name: Restore Maven Cache Dependency
    #    uses: skjolber/maven-cache-github-action@v1
    #    with:
    #      step: restore

     - name: Running Testing
       run: mvn clean test verify

    #  - name: Preparing Code Coverage Reports
    #    run: rm -rfv env/cc/html && mv -v target/site/jacoco env/cc/html/

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
     
     - name: Build Docker Image for Code Coverage
       uses: docker/build-push-action@v2
       with:
         context: ./env/cc/
         tags: irdaislakhuafa/backend-api-lms:latest
         push: true
      
    #  - name: Save Maven Cache Dependency
    #    uses: skjolber/maven-cache-github-action@v1
    #    with:
    #      step: save

  build: 
   name: Build Docker Image with App
   runs-on: ubuntu-latest
   needs: tests
   steps:
     - name: Clone repository to github build enviroment
       uses: actions/checkout@v1